  ret = libusb_control_transfer(ctx->dev_handle, 0x00000080, 0, 0x00000000, 0, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000080, 0, 0x00000000, 0, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 7, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 8, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 6, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 3, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 2, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 6, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 9, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 3, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 3, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 3, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 3, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 3, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 3, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 10, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 8, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 257, data, 6656, 1000);
  fprintf_data(stderr, "ctrl in:", data, 6656);

  if (ret != 6656) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 258, data, 6656, 1000);
  fprintf_data(stderr, "ctrl in:", data, 6656);

  if (ret != 6656) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 6, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 11, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 0, 0x00000001, 4, (unsigned char[]){ 0x0 }, 0, 1000);
  if (ret != 0) {
    debug_printf("strl out: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 11, data, 514, 1000);
  fprintf_data(stderr, "ctrl in:", data, 514);

  if (ret != 514) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

  ret = libusb_control_transfer(ctx->dev_handle, 0x00000021, 192, 0x00000001, 4, data, 517, 1000);
  fprintf_data(stderr, "ctrl in:", data, 517);

  if (ret != 517) {
    debug_printf("ctrl in: ret == %i\n", ret);
  }

